# Generated by Django 5.2.2 on 2025-06-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('corte', 'Corte de pelo'), ('corte_lavado', 'Corte y lavado')], default='corte', max_length=20),
        ),
    ]
